### PR TITLE
use vendor/nostr-types and vendor/nip44 for explicit version control

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
this PR includes a make config as well

Screen Shot 2023-12-10 at 1 37 14 PM

**Comment by RandyMcMillan** [comment]
this PR includes a base GitHub Actions config

https://github.com/gnostr-org/gnostr-bins/actions/runs/7159592802

**Comment by RandyMcMillan** [comment]
`make cargo-i`

installs and makes nostr-bin commands available

https://github.com/mikedilger/nostr-bins/assets/152159/0212dac1-3fbe-438a-8a2a-4340bfa79c36

**Comment by mikedilger** [comment]
It is nice to see somebody benefit from this repo.

That is a lot of work to use a different build system. That might be useful for you, but it's not useful for me upstream. So I'd prefer you keep these changes downstream at gnostr-org.

**Pull request closed without merging**
